version: '3'
services:
  keystone:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
        - ./backend/keystone.js:/usr/src/app/keystone.js
        - ./backend/models:/usr/src/app/models
        - ./backend/routes:/usr/src/app/routes
        - ./backend/updates:/usr/src/app/updates
    ports:
      - "3000:3000"